version: "3"

services:
  nginx:
    build: ./nginx/
    container_name: nginx-container
    ports:
      - 6666:80
    volumes:
      - ./www/html/:/var/www/html
    networks:
      - backend
      - frontend
  php:
    image: php:7.0-fpm
    container_name: php-container
    expose:
      - 9000
    volumes:
      - ./www/html/:/var/www/html
    networks:
      - backend
  mysql:
    image: mysql:latest
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
        MYSQL_USER: test
        MYSQL_PASSWORD: ${MYSQL_PASS}
    networks:
      - backend
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
    ports:
      - 6001:80
    networks:
      - backend

networks:
  frontend:
  backend: