#ustawienie wersji compose'a
version: "3"


services:
#serwer nginx'a
  nginx:
    # builduje dockefile znajdującego się w podanym folderze
    build: ./nginx/
    # ustawia nazwę kontenera
    container_name: nginx-container
    #ustawienie portu
    ports:
      - 6666:80
    #ustawienie wolumenu który wskazuje jaki katalog ma być wyświetlony przez ngixna
    volumes:
      - ./www/html/:/var/www/html
    # dołączenie do dwóch sieci
    networks:
      - backend
      - frontend
  # serwis php
  php:
    # obraz php-fpm
    image: php:7.0-fpm
    # nazwanie kontenera
    container_name: php-container
    # expose na port 9000, podobny port znajduje się w pliku default.conf
    expose:
      - 9000
    #ustawienie wolumenu który wskazuje jaki katalog ma być wyświetlony przez php
    volumes:
      - ./www/html/:/var/www/html
    # podłączenie do sieci backend
    networks:
      - backend
  # serwis mysql
  mysql:
    image: mysql:latest
    # ustawienie zmiennych środowiskowych
    environment:
      # zmienne w ${} wskazują na plik .env
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
        # nazwa usera
        MYSQL_USER: test
        # haslo usera
        MYSQL_PASSWORD: ${MYSQL_PASS}
    # podłączenie do sieci backend
    networks:
      - backend
  # serwis phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    # ustawienie zmiennych środowiskowych
    environment:
      # określenie hosta MySQL, wskazuje na usługę mysql 
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      # ustawienie portu
    ports:
      - 6001:80
    # ustawienie sieci backend
    networks:
      - backend

# utworzone sieci
networks:
  frontend:
  backend: